Controllers/WidgetsWinstantPayInvoiceController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Nop.Core;
using Nop.Core.Domain.Catalog;
using Nop.Core.Domain.Customers;
using Nop.Plugin.Widgets.WinstantPayInvoice.Models;
using Nop.Plugin.Widgets.WinstantPayInvoice.Services;
using Nop.Services.Common;
using Nop.Services.Configuration;
using Nop.Services.Customers;
using Nop.Services.Localization;
using Nop.Services.Logging;
using Nop.Services.Messages;
using Nop.Services.Orders;
using Nop.Services.Security;
using Nop.Web.Areas.Admin.Models.Customers;
using Nop.Web.Framework;
using Nop.Web.Framework.Controllers;

namespace Nop.Plugin.Widgets.WinstantPayInvoice.Controllers
{
    [Area(AreaNames.Admin)]
    public class WidgetsWinstantPayInvoiceController : BasePluginController
    {
        private readonly ILocalizationService _localizationService;
        private readonly INotificationService _notificationService;
        private readonly IPermissionService _permissionService;
        private readonly ISettingService _settingService;
        private readonly IStoreContext _storeContext;
        private readonly IOrderProcessingService _orderProcessingService;
        private readonly IOrderService _orderService;
        private readonly WinstantPayInvoiceSettings _invoiceSettings;
        private readonly WinstantPayHttpClient _winstantPayHttpClient;
        private readonly ILogger _logger;
        private readonly ICustomerAttributeService _customerAttributeService;
        private readonly IGenericAttributeService _genericAttributeService;
        private readonly ICustomerAttributeParser _customerAttributeParser;
        private readonly WinstantPayInvoiceManager _winstantPayInvoiceManager;
        private readonly IEncryptionService _encryptionService;

        public WidgetsWinstantPayInvoiceController(ILocalizationService localizationService,
            INotificationService notificationService,
            IPermissionService permissionService,
            ISettingService settingService,
            IStoreContext storeContext,
            IOrderProcessingService orderProcessingService,
            IOrderService orderService,
            ILogger logger,
            WinstantPayInvoiceSettings invoiceSettings,
            WinstantPayHttpClient winstantPayHttpClient,
            ICustomerAttributeService customerAttributeService,
            IGenericAttributeService genericAttributeService,
            ICustomerAttributeParser customerAttributeParser,
            WinstantPayInvoiceManager winstantPayInvoiceManager,
            IEncryptionService encryptionService)
        {
            _localizationService = localizationService;
            _notificationService = notificationService;
            _permissionService = permissionService;
            _settingService = settingService;
            _storeContext = storeContext;
            _orderProcessingService = orderProcessingService;
            _orderService = orderService;
            _invoiceSettings = invoiceSettings;
            _winstantPayHttpClient = winstantPayHttpClient;
            _logger = logger;
            _customerAttributeService = customerAttributeService;
            _genericAttributeService = genericAttributeService;
            _customerAttributeParser = customerAttributeParser;
            _winstantPayInvoiceManager = winstantPayInvoiceManager;
            _encryptionService = encryptionService;
        }

        public IActionResult Configure()
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageWidgets))
                return AccessDeniedView();

            //load settings for a chosen store scope
            var storeScope = _storeContext.ActiveStoreScopeConfiguration;
            var invoiceSettings = _settingService.LoadSetting<WinstantPayInvoiceSettings>(storeScope);
            var decryptedPassword = _encryptionService.DecryptText(_invoiceSettings.Password);
            
            var model = new ConfigurationModel
            {
                Username = invoiceSettings.Username,
                Password = decryptedPassword,
                WPayId = invoiceSettings.WPayId,
                Domain = invoiceSettings.Domain,
                WebServiceUrl = invoiceSettings.WebServiceUrl,
                ActiveStoreScopeConfiguration = storeScope,
                IsShowGetInvoiceStatusButtonOnAdminOrderDetailPage = invoiceSettings.IsShowGetInvoiceStatusButtonOnAdminOrderDetailPage,
                IsShowSendInvoiceToWinstantPayButtonOnAdminOrderDetailPage = invoiceSettings.IsShowSendInvoiceToWinstantPayButtonOnAdminOrderDetailPage,
                IsShowViewInvoiceButtonOnCustomerOrderDetailPage = invoiceSettings.IsShowViewInvoiceButtonOnCustomerOrderDetailPage,
                IsSendInvoiceToWinstantPayWhenOrderPlaced = invoiceSettings.IsSendInvoiceToWinstantPayWhenOrderPlaced,
                Company = invoiceSettings.Company,
                StreetAddress = invoiceSettings.StreetAddress,
                City = invoiceSettings.City,
                State = invoiceSettings.State,
                Country = invoiceSettings.Country,
                PostalCode = invoiceSettings.PostalCode,
                Email = invoiceSettings.Email,
                Phone = invoiceSettings.Phone
            };

            if (storeScope > 0)
            {
                model.Username_OverrideForStore = _settingService.SettingExists(invoiceSettings, x => x.Username, storeScope);
                model.Password_OverrideForStore = _settingService.SettingExists(invoiceSettings, x => x.Password, storeScope);
                model.WPayId_OverrideForStore = _settingService.SettingExists(invoiceSettings, x => x.WPayId, storeScope);
                model.Domain_OverrideForStore = _settingService.SettingExists(invoiceSettings, x => x.Domain, storeScope);
                model.WebServiceUrl_OverrideForStore = _settingService.SettingExists(invoiceSettings, x => x.WebServiceUrl, storeScope);
                model.IsShowGetInvoiceStatusButtonOnAdminOrderDetailPage_OverrideForStore = _settingService.SettingExists(invoiceSettings, x => x.IsShowGetInvoiceStatusButtonOnAdminOrderDetailPage, storeScope);
                model.IsShowSendInvoiceToWinstantPayButtonOnAdminOrderDetailPage_OverrideForStore = _settingService.SettingExists(invoiceSettings, x => x.IsShowSendInvoiceToWinstantPayButtonOnAdminOrderDetailPage, storeScope);
                model.IsShowViewInvoiceButtonOnCustomerOrderDetailPage_OverrideForStore = _settingService.SettingExists(invoiceSettings, x => x.IsShowViewInvoiceButtonOnCustomerOrderDetailPage, storeScope);
                model.IsSendInvoiceToWinstantPayWhenOrderPlaced_OverrideForStore = _settingService.SettingExists(invoiceSettings, x => x.IsSendInvoiceToWinstantPayWhenOrderPlaced, storeScope);
                model.Company_OverrideForStore = _settingService.SettingExists(invoiceSettings, x => x.Company, storeScope);
                model.StreetAddress_OverrideForStore = _settingService.SettingExists(invoiceSettings, x => x.StreetAddress, storeScope);
                model.City_OverrideForStore = _settingService.SettingExists(invoiceSettings, x => x.City, storeScope);
                model.State_OverrideForStore = _settingService.SettingExists(invoiceSettings, x => x.State, storeScope);
                model.Country_OverrideForStore = _settingService.SettingExists(invoiceSettings, x => x.Country, storeScope);
                model.PostalCode_OverrideForStore = _settingService.SettingExists(invoiceSettings, x => x.PostalCode, storeScope);
                model.Email_OverrideForStore = _settingService.SettingExists(invoiceSettings, x => x.Email, storeScope);
                model.Phone_OverrideForStore = _settingService.SettingExists(invoiceSettings, x => x.Phone, storeScope);
            }

            return View("~/Plugins/Widgets.WinstantPayInvoice/Views/Configure.cshtml", model);
        }

        [HttpPost]
        public IActionResult Configure(ConfigurationModel model)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageWidgets))
                return AccessDeniedView();

            //load settings for a chosen store scope
            var storeScope = _storeContext.ActiveStoreScopeConfiguration;
            var invoiceSettings = _settingService.LoadSetting<WinstantPayInvoiceSettings>(storeScope);

            invoiceSettings.Username = model.Username;
            invoiceSettings.WPayId = model.WPayId;
            invoiceSettings.Domain = model.Domain;
            invoiceSettings.WebServiceUrl = model.WebServiceUrl;
            invoiceSettings.IsShowGetInvoiceStatusButtonOnAdminOrderDetailPage = model.IsShowGetInvoiceStatusButtonOnAdminOrderDetailPage;
            invoiceSettings.IsShowSendInvoiceToWinstantPayButtonOnAdminOrderDetailPage = model.IsShowSendInvoiceToWinstantPayButtonOnAdminOrderDetailPage;
            invoiceSettings.IsShowViewInvoiceButtonOnCustomerOrderDetailPage = model.IsShowViewInvoiceButtonOnCustomerOrderDetailPage;
            invoiceSettings.IsSendInvoiceToWinstantPayWhenOrderPlaced = model.IsSendInvoiceToWinstantPayWhenOrderPlaced;
            invoiceSettings.Company = model.Company;
            invoiceSettings.StreetAddress = model.StreetAddress;
            invoiceSettings.City = model.City;
            invoiceSettings.State = model.State;
            invoiceSettings.Country = model.Country;
            invoiceSettings.PostalCode = model.PostalCode;
            invoiceSettings.Email = model.Email;
            invoiceSettings.Phone = model.Phone;

            /* We do not clear cache after each setting update.
             * This behavior can increase performance because cached settings will not be cleared 
             * and loaded from database after each update */

Views/Configure.cshtml
@model Nop.Plugin.Widgets.WinstantPayInvoice.Models.ConfigurationModel

@{
    Layout = "_ConfigurePlugin";
}

@await Component.InvokeAsync("StoreScopeConfiguration")
<form asp-controller="WidgetsWinstantPayInvoice" asp-action="Configure" method="post">
    <div class="panel-group">
        <div class="panel panel-default">
            <div class="panel-body">
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="Username_OverrideForStore" asp-input="Username" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="Username" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="Username" />
                        <span asp-validation-for="Username"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="Password_OverrideForStore" asp-input="Password" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="Password" />
                    </div>
                    <div class="col-md-9">
                        <div class="input-group">
                            <nop-editor asp-for="Password" />
                            <div class="input-group-btn">
                                @if (!String.IsNullOrEmpty(Model.Username))
                                {
                                    <button type="submit" name="changepassword" class="btn btn-info">
                                        @T("Admin.Customers.Customers.Fields.Password.Change")
                                    </button>
                                }
                            </div>

                        </div>
                        <span asp-validation-for="Password"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="WPayId_OverrideForStore" asp-input="WPayId" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="WPayId" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="WPayId" />
                        <span asp-validation-for="WPayId"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="Domain_OverrideForStore" asp-input="Domain" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="Domain" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="Domain" />
                        <span asp-validation-for="Domain"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="WebServiceUrl_OverrideForStore" asp-input="WebServiceUrl" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="WebServiceUrl" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="WebServiceUrl" />
                        <span asp-validation-for="WebServiceUrl"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="Company_OverrideForStore" asp-input="Company" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="Company" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="Company" />
                        <span asp-validation-for="Company"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="StreetAddress_OverrideForStore" asp-input="StreetAddress" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="StreetAddress" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="StreetAddress" />
                        <span asp-validation-for="StreetAddress"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="City_OverrideForStore" asp-input="City" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="City" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="City" />
                        <span asp-validation-for="City"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="State_OverrideForStore" asp-input="State" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="State" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="State" />
                        <span asp-validation-for="State"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="Country_OverrideForStore" asp-input="Country" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="Country" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="Country" />
                        <span asp-validation-for="Country"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="PostalCode_OverrideForStore" asp-input="PostalCode" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="PostalCode" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="PostalCode" />
                        <span asp-validation-for="PostalCode"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="Email_OverrideForStore" asp-input="Email" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="Email" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="Email" />
                        <span asp-validation-for="Email"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="Phone_OverrideForStore" asp-input="Phone" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="Phone" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="Phone" />
                        <span asp-validation-for="Phone"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="IsShowViewInvoiceButtonOnCustomerOrderDetailPage_OverrideForStore" asp-input="IsShowViewInvoiceButtonOnCustomerOrderDetailPage" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="IsShowViewInvoiceButtonOnCustomerOrderDetailPage" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="IsShowViewInvoiceButtonOnCustomerOrderDetailPage" />
                        <span asp-validation-for="IsShowViewInvoiceButtonOnCustomerOrderDetailPage"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="IsShowGetInvoiceStatusButtonOnAdminOrderDetailPage_OverrideForStore" asp-input="IsShowGetInvoiceStatusButtonOnAdminOrderDetailPage" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="IsShowGetInvoiceStatusButtonOnAdminOrderDetailPage" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="IsShowGetInvoiceStatusButtonOnAdminOrderDetailPage" />
                        <span asp-validation-for="IsShowGetInvoiceStatusButtonOnAdminOrderDetailPage"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="IsShowSendInvoiceToWinstantPayButtonOnAdminOrderDetailPage_OverrideForStore" asp-input="IsShowSendInvoiceToWinstantPayButtonOnAdminOrderDetailPage" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="IsShowSendInvoiceToWinstantPayButtonOnAdminOrderDetailPage" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="IsShowSendInvoiceToWinstantPayButtonOnAdminOrderDetailPage" />
                        <span asp-validation-for="IsShowSendInvoiceToWinstantPayButtonOnAdminOrderDetailPage"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="IsSendInvoiceToWinstantPayWhenOrderPlaced_OverrideForStore" asp-input="IsSendInvoiceToWinstantPayWhenOrderPlaced" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="IsSendInvoiceToWinstantPayWhenOrderPlaced" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="IsSendInvoiceToWinstantPayWhenOrderPlaced" />
                        <span asp-validation-for="IsSendInvoiceToWinstantPayWhenOrderPlaced"></span>
                    </div>
                </div>

            </div>
        </div>               
        <div class="panel panel-default">
            <div class="panel-body">
                <div class="form-group">
                    <div class="col-md-9 col-md-offset-3">
                        <input type="submit" name="save" class="btn bg-blue" value="@T("Admin.Common.Save")" />
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

Views/PublicInfo.cshtml
@model Nop.Plugin.Widgets.WinstantPayInvoice.Models.PublicInfoModel

@if (Model.IsAdminOrdersList)
{
    <a asp-route="Plugin.Widgets.WinstantPayInvoice.GetStatus" asp-route-orderId="@Model.OrderId" class="btn bg-green">
        <i class="fa fa-file-pdf-o"></i>
        @T("Plugins.Widgets.Invoice.SendMultipleInvoicesButton.Text")
    </a>
}
else if (!(Model.IsInvoiceNumberExisted))
{
    <a asp-route="Plugin.Widgets.WinstantPayInvoice.Create" asp-route-orderId="@Model.OrderId" class="btn bg-green">
        <i class="fa fa-file-pdf-o"></i>
        @T("Plugins.Widgets.WinstantPayInvoice.SendButton.Text")
    </a>
}
else if (Model.OrderId > 0)
{
    <a asp-route="Plugin.Widgets.Invoice.GetStatus" asp-route-orderId="@Model.OrderId" class="btn bg-green">
        <i class="fa fa-file-pdf-o"></i>
        @T("Plugins.Widgets.WinstantPayInvoice.GetStatusButton.Text")
    </a>
}

Views/PublicInfoAdminOrderDetails.cshtml
@model Nop.Plugin.Widgets.WinstantPayInvoice.Models.PublicInfoModel

@if (!Model.IsInvoiceNumberExisted)
{
    if (Model.IsShowSendInvoiceToWinstantPayButtonOnAdminOrderDetailPage)
    {
    <a asp-route="Plugin.Widgets.WinstantPayInvoice.Create" asp-route-orderId="@Model.OrderId" class="btn bg-green">
        <i class="fa fa-file-pdf-o"></i>
        @T("Plugins.Widgets.WinstantPayInvoice.SendButton.Text")
    </a>
    }
}
else if (Model.OrderId > 0)
{
    if (Model.IsShowGetInvoiceStatusButtonOnAdminOrderDetailPage)
    {
        <a asp-route="Plugin.Widgets.WinstantPayInvoice.GetStatus" asp-route-orderId="@Model.OrderId" class="btn bg-green">
            <i class="fa fa-file-pdf-o"></i>
            @T("Plugins.Widgets.WinstantPayInvoice.GetStatusButton.Text")
        </a>
    }
}

Views/PublicInfoAdminOrderList.cshtml
<a asp-route="Plugin.Widgets.WinstantPayInvoice.GetStatus" class="btn bg-green">
    <i class="fa fa-file-pdf-o"></i>
    @T("Plugins.Widgets.WinstantPayInvoice.SendMultipleInvoicesButton.Text")
</a>

Views/PublicInfoOrderDetail.cshtml
@model Nop.Plugin.Widgets.WinstantPayInvoice.Models.PublicInfoOrderDetailModel
@if (Model.IsInvoiceExisted)
{
    <div class="actions">
        <input type="button" value="@T("Plugins.Widgets.WinstantPayInvoice.ViewInvoice.Text")" class="button-1 re-order-button" onclick="setLocation('@Model.InvoicePublicUrl')" />
    </div>
}

Views/_PublicInfo.SliderLine.cshtml
@model Nop.Plugin.Widgets.WinstantPayInvoice.Models.PublicInfoModel

@{
    var pictureUrl = ViewData["pictureUrl"]?.ToString() ?? "";
    var link = ViewData["link"]?.ToString() ?? "";
    var dataTransition = ViewData["dataTransition"]?.ToString() ?? "";
    var text = ViewData["text"]?.ToString() ?? "";
    var alttext = ViewData["alttext"]?.ToString() ?? "";

    if (!string.IsNullOrEmpty(pictureUrl))
    {
        if (!string.IsNullOrEmpty(link))
        {
            <a href="@link" aria-label="@alttext">
                <img src="@pictureUrl" data-thumb="@pictureUrl" data-transition="@dataTransition" alt="@alttext" title="@text" />
            </a>
        }
        else
        {
            <img src="@pictureUrl" data-thumb="@pictureUrl" data-transition="@dataTransition" alt="@alttext" title="@text" />
        }
    }
}